### ISSUE TITLE
Landing page is disfigured

### ISSUE THREAD

**Issue by avif** [dchqinc/dchq-io-issue-tracker#1]
URL: https://www.dchq.io/landing/index.html
![dchq cloud application platform - linux containers - docker paas](https://cloud.githubusercontent.com/assets/3197809/11931391/2d27c052-a7f5-11e5-9b22-b50b0feb3bca.jpg)

Notice that the top cover image is not full width.

**Comment by dchqinc** [comment]
Thanks so much for the feedback. We'll make sure to fix this in the next build -- coming in a few days.
