### ISSUE TITLE
Last name missing in profile

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#2]
Registered a new user in QE Entered full name as 'Mohammed Sajid Ali Khan'.
After login, In the My Profile page it is showing First name as Mohammed and Last name as Sajid only.
Last Part of the name 'Ali Khan'  entered while registering is missing.

**Comment by intesar** [comment]
Closing this bug since user can update name in the profile page.
