### ISSUE TITLE
 No error message is displayed on entering invalid email or password on Sign In page

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#26]
I signed in by entering invalid email or password in respective fields on Sign In page. On entering wrong email or password in Sign In page, no action is done, rather the page is getting refreshed or displaying the same page. The page should display an error message on entering invalid email or password.

**Comment by intesar** [comment]
Removed email validation to support tenant as prefix.
