### ISSUE TITLE
NGINX is shown running in Reports page, even after the host is destroyed. 

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#27]
I created a host and deployed an NGINX blueprint. I can see it in Live Apps page. Later I destroyed the host. After destroying the host, now my Live Apps page is empty. Actually it should stop running the apps, but when I checked in Reports Page, the NGINX is shown running in the Report page, even after the host destroyed.

**Comment by intesar** [comment]
Yes, destroying VM will destroy app as well.
