### ISSUE TITLE
Entitled Users function is not working

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#28]
I created two different users, and I also created a cluster in one user. Now I wanted to use this cluster for another user by selecting Entitled Users 'Everyone'. This should actually show my cluster in another user also. On selecting Entitled Users 'Everyone', it is not showing my cluster to another user which is also created by me. Cluster is not shown to other users on selecting the Entitled Users 'Everyone' button/function.

**Comment by intesar** [comment]
Not a bug, Only entitled clusters with active servers are visible.
