### ISSUE TITLE
is REST API working?

### ISSUE THREAD

**Issue by o14pmhvdwgag** [dchqinc/dchq-io-issue-tracker#36]
reffering to https://dchq.readme.io/docs, I tried to use REST API from commandline using curl.
but always it fails with error code 7 "Failed to connect to host or proxy".
is REST API working? or am I using it in wrong way?

**Comment by intesar** [comment]
Can you try something like this.

curl -u email:password -i -H "Accept: application/json" "https://www.dchq.io/api/1.0/apps"
curl -u accessKey:secretKey -i -H "Accept: application/json" "https://www.dchq.io/api/1.0/apps"

Please check the host you're connecting to and the credentials.

**Comment by o14pmhvdwgag** [comment]
thank you for the reply, and it works. i appreciate it.
