### ISSUE TITLE
Star & Unstar Action not working on BluePrints

### ISSUE THREAD

**Issue by sujithagandla** [dchqinc/dchq-io-issue-tracker#37]

**Comment by sujithagandla** [comment]
when try to Star or Unstar the "Blueprints" from Library page  showing message "User is not Entitled to blueprint" .

**Comment by abedeen** [comment]
Fixed

**Comment by abedeen** [comment]
please varify and close

**Comment by sujithagandla** [comment]
it is still unchanged.

**Comment by sujithagandla** [comment]
it is working
