### ISSUE TITLE
Totalling of Memory of containers is in correct

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#41]
Deploy an application. Application runs successfully showing containers status and values. Totalling of Memory of containers is in correct.

**Comment by abedeen** [comment]
Could you please share steps to get error.

in apps page  information is correct here

![image](https://cloud.githubusercontent.com/assets/17420502/19696679/d1930396-9b05-11e6-954c-8862afd55d36.png)
