### ISSUE TITLE
Cloud Providers - Mouse hover on +/New button, is not displaying any message asking to create a new Cloud Provider

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#42]
Click on Cloud Providers item to view list of Cloud Providers. User finds a +/New button on the extreme right top of the page. Mouse hover on the +/New button, it should display message asking to create a new Cloud Provider, but is not showing any message.

**Comment by abedeen** [comment]
get a confirmation from intesar bhai for this functionality. it needs to be added to all pages.

**Comment by abedeen** [comment]
Fixed
