### ISSUE TITLE
Library Page - Servers count is mismatching while selecting cluster for deployment.

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#43]
Deploy an application. At the time of deployment, the page ask to choose a cluster. Clusters with detailed information is displayed in the drop-down list.  On selecting anyone, the detailed information about clusters is mismatching. Basically there were two servers running, but  when we  select cluster for deployment, sometimes its showing only one server running in the cluster's detailed information.

**Comment by abedeen** [comment]
Could you please share it on ur screen
