### ISSUE TITLE
DCHQ Log In Page - Enter valid email & click on 'forgot p/w' button,  page displays 'Error processing request' message

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#44]
Log In to dchq.io with valid email and no p/w. User entered valid email but forgot p/w, clicking on 'forgot p/w' button, Hyperform page is opened. On entering valid email in Hyperform page & clicking on 'forgot p/w' button, the page is displaying 'Error processing request' message.

**Comment by abedeen** [comment]
On invalid email
![image](https://cloud.githubusercontent.com/assets/17420502/19761540/14e25fd0-9c54-11e6-94f1-7be645222a14.png)

on valid email 2nd time
![image](https://cloud.githubusercontent.com/assets/17420502/19761590/3557ad1a-9c54-11e6-8eac-fb7c3a7b34a1.png)
