### ISSUE TITLE
DCHQ Log In Page - No error message displayed on entering invalid email or password

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#45]
Log In to dchq.io with invalid email or p/w. The page should display error message like 'Invalid email or password'. The page is not showing any error message on entering invalid email or password, instead is displaying log in page.

**Comment by abedeen** [comment]
Fixed
![image](https://cloud.githubusercontent.com/assets/17420502/19760205/30b6a082-9c4e-11e6-93cf-35d8838f80e8.png)
