### ISSUE TITLE
Apps Page - 'show comments' function is not working

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#46]
Customize any application. Find 'show comments' button at the bottom of the page. Click on it to add comments. Comments are added one after the other but no comment is shown. After adding comments to the list, it should show all the comments in general, but it is not showing any comment. 'show comments' function is not working

**Comment by abedeen** [comment]
Fixed : Need to discuss the logic 
Issue: 
At the time of sending Notification .the application was searchig for the creator name.since it was unable to search for creator it was unable to show comment.
Lets get to meeting before close.
