### ISSUE TITLE
Networks Page - Inspect button function is not working 

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#47]
Click on Networks item. Click on drop down and select Inspect button. There's no change in the page on clicking Inspect button. A small window must open which should contains details about Networks. Inspect button function is not working.

**Comment by shoukathmd** [comment]
![image](https://cloud.githubusercontent.com/assets/4810966/19718495/2a2b53fa-9b83-11e6-8077-50727d75af12.png)

Not able to reproduce in chrome browser. Able to see the output in Popup as expected
