### ISSUE TITLE
Volumes Page - Inspect button function is not working 

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#48]
Click on Volumes item. Click on drop down and select Inspect button. There's no change in the page on clicking Inspect button. A small window must open which should contains details about Volumes. Inspect button function is not working.

**Comment by shoukathmd** [comment]
![image](https://cloud.githubusercontent.com/assets/4810966/19718301/661f50ce-9b82-11e6-98fa-ca1986f9db7b.png)


Using chrome browser and able to see the inspect output in popup. Attaching screenshot for reference

**Comment by intesar** [comment]
Close bugs if they're not reproducible. File separate bugs for different browsers.
