### ISSUE TITLE
Apps Page - Expand/Collapse button not working accordingly

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#50]
Deploy an application. Expand any one container to see its details. On expanding only one container, all the number of containers are getting expanded, showing details of all the containers. And if one container is minimized, all the others are getting minimized too. Expand button function is not working properly. Similarly Collapse button is also not working accordingly.

**Comment by abedeen** [comment]
Fixed
