### ISSUE TITLE
Machines Page - System Info details are not displayed 

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#51]
Click on Machines item. Select 'System Info' from the drop down. System Info opens in a new window but no details are displayed. Details of System Info, CPU Details, Primary Network, CPU, Memory, Disks are not displayed.

**Comment by abedeen** [comment]
Fixed
![image](https://cloud.githubusercontent.com/assets/17420502/19826413/32236ce8-9da7-11e6-9058-f862a35675e4.png)
![image](https://cloud.githubusercontent.com/assets/17420502/19826416/46cefa22-9da7-11e6-88f8-54ea193f435f.png)
![image](https://cloud.githubusercontent.com/assets/17420502/19826419/56dc4014-9da7-11e6-8c32-043eff20af56.png)
![image](https://cloud.githubusercontent.com/assets/17420502/19826420/5f980aee-9da7-11e6-9824-38a743bed234.png)
