### ISSUE TITLE
Blueprints Page - Yaml code is displayed like a flash, disappears in 1 or 2 secs

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#53]
Click App & Machine on Blueprint item. Click on any blueprint from the list displayed. Click on Action button and select History. History of blueprint and a Yaml button is displayed. Clicking on Yaml button should display  Yaml code. Yaml code is displayed like a flash and disappears in 1 or 2 secs.

**Comment by abedeen** [comment]
Fixed
