### ISSUE TITLE
Users Profile is not displaying ---Recent Activity

### ISSUE THREAD

**Issue by sujithagandla** [dchqinc/dchq-io-issue-tracker#56]
In Dashboard  window-- Recent Activity ,if we click on users name ,users profile window is able to open but it is not displaying the users information. 

![hyperform](https://cloud.githubusercontent.com/assets/16403726/19722503/a39d53bc-9b94-11e6-9838-767d0eefe980.png)

![hyperform1](https://cloud.githubusercontent.com/assets/16403726/19722653/50893dc0-9b95-11e6-9154-1853c857f902.png)

**Comment by abedeen** [comment]
Fixed
![image](https://cloud.githubusercontent.com/assets/17420502/19754166/abac1b44-9c28-11e6-9cd6-bb52011e064a.png)
