### ISSUE TITLE
DCHQ Main Page - Invite Friends function is not working

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#58]
Click on username at top right and select 'Invite Friends' from drop down. New page opens asking to enter friends emails. Adding friends emails, click on Invite button is showing 'Error Inviting Email' or 'Request Failed' message. Invite Friends function is not working.
![invite-friends-1](https://cloud.githubusercontent.com/assets/16450606/19794799/fd0d1c3e-9cf2-11e6-9c45-78714846c802.png)
![invite-friends-2](https://cloud.githubusercontent.com/assets/16450606/19794806/081bebf0-9cf3-11e6-9824-201b3bcb9ffc.png)

**Comment by intesar** [comment]
Let's make this PILOT feature.

**Comment by abedeen** [comment]
We do not have access to the link in prodution.

Intesar bhai , This feature is in PILOT2 . please let me know if  we need to move in PILOT.

When we try to invite friends more than 1 time we get errors.

Meanwhile its working in localmachine pls find the screenshot 
![image](https://cloud.githubusercontent.com/assets/17420502/19795910/c0473536-9cfd-11e6-99d6-0dba60f789ff.png)
