### ISSUE TITLE
Blueprints Page - Not showing Modified Date of blueprint 

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#59]
Edit any blueprint from the list displayed. Click on Action button and select History. History of blueprint is displayed with ID, Author & Modified Date fields. But Modified Date is blank. Not showing Modified Date of blueprint.
![modified date-3](https://cloud.githubusercontent.com/assets/16450606/19794828/40255ea0-9cf3-11e6-9736-b3c5ebaba516.png)

**Comment by abedeen** [comment]
fixed
![image](https://cloud.githubusercontent.com/assets/17420502/19796055/2828ac24-9cff-11e6-9b09-28cc900c66ec.png)
