### ISSUE TITLE
Blueprints - Plugins Page - Import function is not working

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#60]
Click +/New, select shell from drop down to create a new plugin. Click on Action button at top right, click Import. Import Plugin page is opened asking to Choose File or Import. On clicking Import, is not importing any plugin. Import function is not working. 
![import plugin-4](https://cloud.githubusercontent.com/assets/16450606/19794841/70fb41b6-9cf3-11e6-8290-bab008f5a981.png)

**Comment by abedeen** [comment]
Fixed
screen 1:
![image](https://cloud.githubusercontent.com/assets/17420502/19802914/b257e558-9d23-11e6-8070-1e7c32bf3ba2.png)
 screen 2:
![image](https://cloud.githubusercontent.com/assets/17420502/19802938/d216f9ec-9d23-11e6-90d4-f44ffdbb1b6e.png)
