### ISSUE TITLE
Apps Page - Apps with lengthy names are not looking good

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#66]
Click on Apps item. List of apps is displayed. Apps with lengthy names are not looking good. 
![appslengthyname-15](https://cloud.githubusercontent.com/assets/16450606/19916456/16db30ec-a0e0-11e6-88a3-0b9258d7d1d2.png)

**Comment by intesar** [comment]
Max 40 chars are allowed.
