### ISSUE TITLE
Apps Page - Spelling of Network is incorrect

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#67]
Click on Apps item. Manage any Live App. Click on Down Arrow button present at left side to the containers status table. Clicking on Down Arrow button, a drop down is displayed, in which the spelling of Network is not correct. Spelling of Network is wrongly written as Netowork instead of Network.
![networkspelling-14](https://cloud.githubusercontent.com/assets/16450606/19916511/89f1ac82-a0e0-11e6-9ad5-d0be637656a1.png)

**Comment by luqmanshareef** [comment]
Fixed.  Corrected the spelling.

**Comment by SajidAliKhanMohammed** [comment]
Jazakallah !!!
