### ISSUE TITLE
Apps Page - Cluster Name field should be replaced with Container Name field

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#69]
Click on Apps item. Manage any Live App. Click on Action button, select Scale Out /Scale In from the drop down. List of Containers with other details is displayed. One of the header field name is shown as 'Cluster Name' instead of 'Container Name'. 'Cluster Name' field should be replaced with 'Container Name' field.
![clustername-12](https://cloud.githubusercontent.com/assets/16450606/19916587/67107bf2-a0e1-11e6-8b80-c7aa8a63b490.png)

**Comment by abedeen** [comment]
Fixed

**Comment by SajidAliKhanMohammed** [comment]
Jazakallah !!!
