### ISSUE TITLE
Library Page - List of Starred Blueprints is not shown on filtering with 'Starred'  

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#71]
Click on Library item. Click on Filter and select Starred from drop down. The page should display list of Starred blueprints. Not showing list of Starred Blueprints on filtering with 'Starred'.
![starred-10](https://cloud.githubusercontent.com/assets/16450606/19916766/4f1704c4-a0e3-11e6-8ba9-143866ce89cb.png)

**Comment by abedeen** [comment]
Working here. 
![image](https://cloud.githubusercontent.com/assets/17420502/19957195/7b74afee-a1ba-11e6-91f4-0c857006ccee.png)
