### ISSUE TITLE
Library Page - Click on Create New Cluster is redirected to dchq.io home page

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [dchqinc/dchq-io-issue-tracker#72]
Click on Library item and customize any blueprint. Click on 'Create New Cluster' in order to create a new one. The page is redirected to dchq.io home page instead of opening a form to create a new cluster.
![createnewcluster a -8](https://cloud.githubusercontent.com/assets/16450606/19916825/d2b0f4a2-a0e3-11e6-932e-2bcc266a5b79.png)
![createnewcluster b -9](https://cloud.githubusercontent.com/assets/16450606/19916827/d9bb21f0-a0e3-11e6-9a3f-85e7a084e6bd.png)

**Comment by abedeen** [comment]
Discussed with intesar bhai, Link Removed, Fixed.
